set(CMAKE_COLOR_DIAGNOSTICS ON)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
option(BUILD_EXAMPLES "Build example programs" OFF)
option(BUILD_TESTS "Build test cases" OFF)
option(KFCORE_ENABLE_CUDA "Build CUDA and TensorRT backends" ON)
option(KFCORE_ENABLE_ONNX_CPU "Build ONNX Runtime CPU backends" OFF)
