/* Generated by CMake for the vendored libserialport build. */

#cmakedefine HAVE_SYS_FILE_H 1
#cmakedefine HAVE_REALPATH 1
#cmakedefine HAVE_FLOCK 1
#cmakedefine HAVE_CLOCK_GETTIME 1
#cmakedefine HAVE_STRUCT_SERIAL_STRUCT 1
#cmakedefine HAVE_STRUCT_TERMIOS_C_ISPEED 1
#cmakedefine HAVE_STRUCT_TERMIOS_C_OSPEED 1
#cmakedefine HAVE_STRUCT_TERMIOS2 1
#cmakedefine HAVE_STRUCT_TERMIOS2_C_ISPEED 1
#cmakedefine HAVE_STRUCT_TERMIOS2_C_OSPEED 1
#cmakedefine HAVE_STRUCT_TERMIOX 1

